alias ys="yarn start"
alias y="yarn"
alias yw="yarn watch"
alias yb="yarn build"
alias gs="git status"
alias ga="git add --all"
alias gc="git commit -m"
alias gcb="git checkout -b"
alias gp="git push"
alias grm="git rebase -i master"
alias hg="history 1 -1 | grep"
alias tp="terraform plan"
alias ta="terraform apply"
alias tf="terraform"
alias jw="jest --watch --verbose=true"